# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.5
language: swift
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -scheme SwiftGradientsTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
